### PR TITLE
Update orphan_packages.sh / -Rns may break the system and delete too much deps, -Run is a much better choice

### PR DESCRIPTION
**Pull request by Delor3an91**
### Screenshots / Logs

```text
Paste any relevant logs here (if you have some)
```

### Fixed bug

Fixes "issue_URL" (if any)

### Addressed feature request

Closes "issue_URL" (if any)

### CODE REVIEW

**Comment by Delor3an91** [comment]
-Rns may break the system and delete too much deps, -Run is a much better choice

**Comment by Antiz96** [comment]
Hi @Delor3an91,

Thanks for your proposition!

> -Rns may break the system and delete too much deps, -Run is a much better choice

Can you elaborate? 
`-Rns` shouldn't cause any breakage or deleting too much deps as it only delete deps that are not required by any other packages (including optional dependencies) or wasn't installed explicitly by the user.

From pacman's man page:

> -s, --recursive
> Remove each target specified including all of their dependencies, provided that **(A) they are not
> required by other packages**; and **(B) they were not explicitly installed by the user**. This operation is
> recursive and analogous to a backwards --sync operation, and **it helps keep a clean system without
> orphans.** If you want to omit condition (B), pass this option twice.

The `-s` option should be a safe and appropriate choice to clean orphan packages with Arch-Update. The verification done by `-u` (namely that the target is not require by any other packages) is already covered as the targets are orphan packages (which are, by definition, not required by any other packages) and the same verification is done by `-s` for their dependencies (see point `(A)` in the above snippet from the man page).

The `-u, --unneeded` option is mostly useful when removing a group package and make sure to keep packages from the said group that are still required by other packages on the system (see the `-u, --unneeded` option is pacman's man page), which is irrelevant for the Arch-Update "clean orphans" step.

**Comment by Antiz96** [comment]
I slightly edited my above comment to add additional information, just so you know.

**Comment by Delor3an91** [comment]
Hi @Antiz96,

You're welcome!

The `-s` will effectively remove deps that are not **required** and that may cause problems.

From my own experience of that command, `-s` had removed deps that weren't explicitly installed and it's supposed to do it. So it do the job!

**But**, some cross packages on your system may have the use of those deps packages that are still useful to them but not explicitly needed by them. So, the '-s' will delete too much packages that may still be important for other ones to work as they usually do until You run a `-Rns` for the first time on your system.

I find better to do a 'while' with `pacman -Run $(pacman -Qdtq)` until the output is cleared.
This way You will not lose any deps functionality.


If one day You remove manually a package, You may compare the output of a `pacman -Rns package_name` and a `pacman -Run package_name` and You may see the differences between those.

I invite You to run some tests in a VM or a test system to see that. with the `-Run` and with the `-Rns` options to compare.
I advice You to delete a package with `-Run` and then delete manually the orphans with `pacman -Run$(pacman -Qdtq)`. Repeat the `pacman -Run $(pacman -Qdtq)` until the output is cleared and only then try to run a `pacman -Rns $(pacman -Qdtq)`. I guess the output will be cleared too.

An **orphan** package is not useful to any package so it is true an orphan is **unneeded**.
**But** a **deps** one, may still be useful.


Wish You well

**Comment by Antiz96** [comment]
As said already, `-Rns` is the proper choice / option to delete orphan packages. 

After a second thought, I think you might be confusing `-s, --recursive` and `-c, --cascade`. Only the latter could lead to undesired packages removal and it is not used anywhere in Arch-Update.

As a side note, I think it's also fair to remind that, regardless if recursivity is involved or not, users are expected to read pacman's output and explicitly accept the outcome. Neither pacman nor Arch-Update are taking any decision by themselves.
If a package that you would like to keep is ever listed as orphaned (or is included in the recursive deletion implied by `-s`), you shouldn't accept its deletion and mark it as "explicitly installed" (`pacman -D --as-explicit *package name*`) so it cannot ever be listed as orphan anymore.

With that said, one last time, thanks anyway for your suggestion and your interest towards this project! :)

Allow me to close this pull request.

**Pull request closed without merging**
