### PR TITLE
Add support for updating AUR development packages with `-d/--devel`

### PR DESCRIPTION
**Pull request by derethil**
- Added support for optional parameters (in any order)
- If the `-d/--devel` flag is provided, the `--devel` flag will be provided to the AUR helper to update development packages
- ~~Added configuration file option `CheckDevelopmentPackages` to always check/update development packages~~
- Updated PO Template file with new source line numbers/new translations.

### CODE REVIEW

**Comment by Antiz96** [comment]
Hi,

Thanks a lot for your great contribution and effort!

I like the idea of a `-d/--devel` option to be able to *occasionally* check/update AUR development packages when running `arch-update`.

However, I'm less sure about the `CheckDevelopmentPackages` option in the configuration file. In my opinion, if one wants AUR development packages to be checked/updated everytime, it should be handled directly at the `yay/paru` level (with the devel option in their respective configuration file) rather than at the `arch-update` level.

**Comment by Antiz96** [comment]
I'm currently away from home, I'll review your changes when I'm back from vacations.

Thanks once again!

**Comment by derethil** [comment]
No problem, that was the one thing I wasn’t sure about as well - makes perfect sense. 

Thanks for the fantastic tool! 🙂

**Review by Antiz96 — APPROVED** [review]
Hi,

I took the time to review your changes and I made the following slight additions/modifications:

- Added the documentation for the new option to the man page
- Modified a bit the option's description in documentation and shell completions
- Reformat a bit the technical implementation of the option within the script in a more simple way to match the current "coding style"
- Added the french translation for the option

Tests are okay, this should now be ready to be merged!
Thanks a lot once again for this great contribution :smiley:

**Pull request merged**
