### PR TITLE
feat: Show the number and the list of pending updates in systray's tooltip

### PR DESCRIPTION
**Pull request by Antiz96**
### Description

Show the number and the list of pending updates in the systray applet tooltip, shown when hovering the mouse over the systray icon.

### Addressed feature request

Closes https://github.com/Antiz96/arch-update/issues/154

### CODE REVIEW

**Comment by Antiz96** [comment]
@trigg Hey :wave: I hope you're doing good!

I'm sorry to bother you with that, I know it's been a while... but do you mind giving this a quick review?  
I've tested it on my side and it works as intended, but if you see any relevant improvements to make, please tell me :)

Thanks in advance!

**Comment by trigg** [comment]
G'Day! 

I've had a look over and run it locally, no issues that I can see. I'd not considered tooltip at all, but this looks like a very good use for it.

**Comment by Antiz96** [comment]
Alright, thanks a lot!

I'm shipping this then :rocket: :tada:

**Review by Antiz96 — COMMENTED** [review]
LGTM

**Pull request merged**
