### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by Delor3an91**
Correction de traduction française.

### CODE REVIEW

**Comment by Antiz96** [comment]
Woops :hand_over_mouth: Thanks for the correction!

**Review by Antiz96 — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by Antiz96** [comment]
Merged :tada:  
I'll release a new version including this fix later today. Thanks again!

**Comment by Antiz96** [comment]
`[v3.2.2](https://github.com/Antiz96/arch-update/releases/tag/v3.2.2)` released, including this fix :)

**Comment by Delor3an91** [comment]
> Woops 🤭 Thanks for the correction!

You're Welcome!

**Pull request merged**
