### PR TITLE
Enable icon themes to supply alternative icons

### PR DESCRIPTION
**Pull request by trigg**
- Install icons in hicolor theme
- Refer to icons by icon name and not filepath
- Copying icons over `arch-update.svg` is replaced with a `sed` command to alter the `Icon` line in the desktop file.

### CODE REVIEW

**Comment by trigg** [comment]
hold up on this, found an edge case I didn't catch before

**Comment by Antiz96** [comment]
Hi,

Thanks a lot for your contribution!

Installing icons in hicolor theme and refering to them with icon name rather than path feels like a good idea.

However, I think the `sed` part won't do.
Replacing text in the .desktop file will require root privileges that won't be granted (either yet or at all) in some cases (e.g. when looking for available updates).
This is why I initially went with this *sketchy* `cp` solution with the icons having the [world readable bit set](https://github.com/Antiz96/arch-update/blob/main/Makefile#L15).

Going further on that, the "changing icon" part has always been a bit *hacky* to be fair and it is often not working as intended for most people (as most panel/taskbar/dock do not support real time refreshing icons anyway...).
To be honest, as I can't think of a proper/better way to handle that at the moment, I am actually considering dropping it altogether in favor of a single "regular/unchanging" icon.

I guess the actual proper way to deal with an icon changing dynamically would be to make a proper systray integration for Arch-Update but I'm unsure how to do that as of now...

**Comment by Antiz96** [comment]
> Yeah, I'm unhappy about the security implication of allowing the user to write into the system `.desktop` file.
> 
Yeah, that would indeed be insecured and unexpected (hence why I initially gave write permissions to icons instead, which is less of a security concern). 

> I'll close this, and look at another way to do it

As I said in my previous comment, I think I'm actually in favor of dropping the  "changing icon" thingy (solving the above concern, as it would not be needed anymore).
As said in that comment as well, I also like the idea of installing the icon in the hicolor them and refering to icons with name instead of path.

Please, feel free to re-open this PR (or a new one) covering the two above points ! I'd be glad merging your efforts :)
I can drop the "icon changing" part in a separate PR (or we can co-author a single PR together if you prefer).

**Comment by trigg** [comment]
> I guess the actual proper way to deal with an icon changing dynamically would be to make a proper systray integration for Arch-Update but I'm unsure how to do that as of now...

That's worth an entire other conversation. I'm not able to start on this immediately, but it'd be something I can write a PR for.

Do you feel more comfortable with python or rust? I could try my hand at c++ but I'm only recently reacquainting myself.

**Comment by Antiz96** [comment]
> 
> > I guess the actual proper way to deal with an icon changing dynamically would be to make a proper systray integration for Arch-Update but I'm unsure how to do that as of now...
> 
> That's worth an entire other conversation. 
>
Indeed.

> I'm not able to start on this immediately, but it'd be something I can write a PR for.
> 
That would be very much appreciated!

> Do you feel more comfortable with python or rust? I could try my hand at c++ but I'm only recently reacquainting myself.
>

Definitely not c++ 😅
I'd probably be more comfortable with python I guess, but if you feel rust is more suited, that will do :)

**Comment by Antiz96** [comment]
> I'm not able to start on this immediately, but it'd be something I can write a PR for.
> 

@trigg Would you mind considering still re-opening that PR (minus the `sed` part) in the mean time? Icon paths are a bit of a pain to deal with in some specific cases so I'd be glad getting rid of them anyway :)

**Pull request closed without merging**
